#include<iostream>
using namespace std;
int main(){

//Define your information
string name = "Shehu Muhammad Alala";
string email = "shehumuhammadalala@gmail.com";
string slack_username = "@shehualala0";
string area of interest = "Genomics"

// Print the information
    cout<<"Name:"<<name<<endl;
    cout<<"email:"<<email<<endl;
    cout<<"Slack Username:"<<slack_username<<endl;
    cout<<"Area of Interest in Bioinformaticcs:"<<area_of_interest<<endl;
return 0;
}

